filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /data/log/node-api/*
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true

processors:
  - add_tags:
      tags: [microservices]

output.logstash:
  hosts: ["logstash:5044"]
